default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: videoamp
  pool: 5

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres
